language: android
sudo: true
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  global:
    - BUILD_STATUS="unspecified"
    - COLON=":"
    - TRAVIS_BUILD_URL="https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"

git:
  submodules: false

# before_install:
#   - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
#   - git submodule init && git submodule update

script:
  - if [ -n "${TRAVIS_PULL_REQUEST}" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      ./gradlew :publication:test --i --S;
    fi

after_success:
  - if [ -n "${TRAVIS_PULL_REQUEST}" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      BUILD_STATUS="build successfully";
    fi
  
after_failure:
  - if [ -n "${TRAVIS_PULL_REQUEST}" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      BUILD_STATUS="build failed";
    fi
  
after_script:
  - |
    # Append comment to github's pull-request
    if [ -n "${TRAVIS_PULL_REQUEST}" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      COMMENT="travis bot$COLON [$BUILD_STATUS]($TRAVIS_BUILD_URL)"
      CURL_H="Authorization$COLON token $GITHUB_TOKEN"
      CURL_D="{\"body\"$COLON \"$COMMENT\"}"
      echo "curl params = curl -H \"$CURL_H\" -X POST -d \"$CURL_D\""
      curl -H "$CURL_H" -X POST -d "$CURL_D" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"
    fi